name: Security check - Bandit

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Security check - Bandit
      uses: ioggstream/bandit-report-artifacts@v1.7.4
      with:
        config_file: pyproject.toml

    # This is optional
    - name: Security check report artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Security report
        path: output/security_report.txt
